### ISSUE TITLE
Command to run in terminal

### ISSUE THREAD

**Issue by mrstephenpace** [so77id/docker-tensorflow-opencv3#3]
What command needs to be run in the terminal? Is it this?

nvidia-docker run -it --rm  --env DISPLAY=$DISPLAY --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" -v=$(pwd)/..:$(pwd)/.. -w=$(pwd) tensorflow-opencv-gpu-py3 /script/to/run; /or/set/of/them

I assume  "/script/to/run; /or/set/of/them" needs to be replaced with something. But what exactly? In other words, what are the specific steps to get this container to work?

**Comment by so77id** [comment]
if you use cpu/gpu version for running you need use this command

**cpu** `docker run -it --rm so77id/tensorflow-opencv-py3:latest-cpu`
**gpu** `nvidia-docker run -it --rm so77id/tensorflow-opencv-py3:latest-gpu`

assuming that use my version in [docker hub](https://hub.docker.com/r/so77id/tensorflow-opencv-py3/)

now if you build using Makefile inside this repository you have two commands

`make build-cpu`/`make build-gpu` for build docker image
and `make run-cpu`/`make run-gpu` for run in terminal 

now the another flags in README you only need use if require more connections with you host computer:

`--env`: this is for share display
`--volume`/'-v': for share folders
`-w`: for workspace folder

**Comment by mrstephenpace** [comment]
Thanks for the quick response! I finally got it working. For any python script I want to run I have to make sure to type "python3" so that it invokes Python 3.5.
